name: Report fly.io environment

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Report fly.io status to Kosli
      run: |
        ./bin/flyio_env_report.sh https://app.kosli.com fly-demo fly-staging
